import type { AuthzGrant } from '../authz/rbac/permissions';
import type { AppRole, PlatformRole, RoleContext, TenantRole } from '../roles/roles';

const tenantRoleGrants: Record<TenantRole, AuthzGrant[]> = {
  company_admin: [
    { permissionKey: 'task.view', scopes: ['global'] },
    { permissionKey: 'task.create', scopes: ['global'] },
    { permissionKey: 'task.update', scopes: ['global'] },
    { permissionKey: 'task.linkEntities', scopes: ['global'] },
    { permissionKey: 'task.followup.schedule', scopes: ['global'] },
    { permissionKey: 'task.bulkReassignOwner', scopes: ['global'] },
    { permissionKey: 'attendance.view', scopes: ['global'] },
    { permissionKey: 'attendance.create', scopes: ['global'] },
    { permissionKey: 'attendance.updateSla', scopes: ['global'] },
    { permissionKey: 'attendance.closeOutOfSla', scopes: ['global'] },
    { permissionKey: 'attendance.convertToTask', scopes: ['global'] },
    { permissionKey: 'attendance.convertToDeadline', scopes: ['global'] },
    { permissionKey: 'team.view', scopes: ['global'] },
    { permissionKey: 'team.assignOwnership', scopes: ['global'] },
    { permissionKey: 'team.reassignPortfolio', scopes: ['global'] },
    { permissionKey: 'portfolio.view', scopes: ['global'] },
    { permissionKey: 'portfolio.assignOwnership', scopes: ['global'] },
    { permissionKey: 'portfolio.reassign', scopes: ['global'] },
    { permissionKey: 'productivity.view', scopes: ['global'] },
    { permissionKey: 'productivity.snapshot', scopes: ['global'] },
    { permissionKey: 'productivity.export', scopes: ['global'] },
    { permissionKey: 'export.tasks', scopes: ['global'] },
    { permissionKey: 'export.attendances', scopes: ['global'] },
    { permissionKey: 'export.productivity', scopes: ['global'] },
    { permissionKey: 'ai.view', scopes: ['global'] },
    { permissionKey: 'ai.summary.generate', scopes: ['global'] },
    { permissionKey: 'ai.recommendation.generate', scopes: ['global'] },
    { permissionKey: 'ai.draft.generate', scopes: ['global'] },
    { permissionKey: 'ai.checklist.suggest', scopes: ['global'] },
    { permissionKey: 'ai.audit.view', scopes: ['global'] },
    { permissionKey: 'ai.budget.manage', scopes: ['global'] },
    { permissionKey: 'bi.view', scopes: ['global'] },
    { permissionKey: 'bi.snapshot.generate', scopes: ['global'] },
    { permissionKey: 'bi.export.generate', scopes: ['global'] },
    { permissionKey: 'timesheet.view', scopes: ['global'] },
    { permissionKey: 'timesheet.entry.create', scopes: ['global'] },
    { permissionKey: 'timesheet.entry.update', scopes: ['global'] },
    { permissionKey: 'timesheet.entry.approve', scopes: ['global'] },
    { permissionKey: 'timesheet.report.view', scopes: ['global'] },
    { permissionKey: 'timesheet.period.close', scopes: ['global'] },
    { permissionKey: 'mobile.feed.view', scopes: ['global'] },
  ],
  manager: [
    { permissionKey: 'task.view', scopes: ['team', 'portfolio'] },
    { permissionKey: 'task.create', scopes: ['team', 'portfolio'] },
    { permissionKey: 'task.update', scopes: ['team', 'portfolio'] },
    { permissionKey: 'attendance.view', scopes: ['team', 'portfolio'] },
    { permissionKey: 'attendance.create', scopes: ['team', 'portfolio'] },
    { permissionKey: 'attendance.updateSla', scopes: ['team', 'portfolio'] },
    { permissionKey: 'team.view', scopes: ['team', 'portfolio'] },
    { permissionKey: 'portfolio.view', scopes: ['portfolio'] },
    { permissionKey: 'productivity.view', scopes: ['team', 'portfolio'] },
    { permissionKey: 'productivity.snapshot', scopes: ['team', 'portfolio'] },
    { permissionKey: 'export.tasks', scopes: ['team', 'portfolio'] },
    { permissionKey: 'export.attendances', scopes: ['team', 'portfolio'] },
    { permissionKey: 'timesheet.view', scopes: ['team', 'portfolio'] },
    { permissionKey: 'timesheet.report.view', scopes: ['team', 'portfolio'] },
  ],
  lawyer: [
    { permissionKey: 'task.view', scopes: ['own', 'team', 'portfolio'] },
    { permissionKey: 'task.create', scopes: ['own', 'team', 'portfolio'] },
    { permissionKey: 'task.update', scopes: ['own', 'team', 'portfolio'] },
    { permissionKey: 'task.linkEntities', scopes: ['own', 'team', 'portfolio'] },
    { permissionKey: 'task.followup.schedule', scopes: ['own', 'team', 'portfolio'] },
    { permissionKey: 'attendance.view', scopes: ['own', 'team', 'portfolio'] },
    { permissionKey: 'attendance.create', scopes: ['own', 'team', 'portfolio'] },
    { permissionKey: 'attendance.updateSla', scopes: ['own', 'team', 'portfolio'] },
    { permissionKey: 'attendance.convertToTask', scopes: ['own', 'team', 'portfolio'] },
    { permissionKey: 'attendance.convertToDeadline', scopes: ['own', 'team', 'portfolio'] },
    { permissionKey: 'team.view', scopes: ['team', 'portfolio'] },
    { permissionKey: 'portfolio.view', scopes: ['portfolio'] },
    { permissionKey: 'productivity.view', scopes: ['own', 'team', 'portfolio'] },
    { permissionKey: 'productivity.snapshot', scopes: ['own', 'team', 'portfolio'] },
    { permissionKey: 'export.tasks', scopes: ['own', 'team', 'portfolio'] },
    { permissionKey: 'export.attendances', scopes: ['own', 'team', 'portfolio'] },
    { permissionKey: 'ai.view', scopes: ['own', 'team', 'portfolio'] },
    { permissionKey: 'ai.summary.generate', scopes: ['own', 'team', 'portfolio'] },
    { permissionKey: 'ai.recommendation.generate', scopes: ['own', 'team', 'portfolio'] },
    { permissionKey: 'ai.draft.generate', scopes: ['own', 'team', 'portfolio'] },
    { permissionKey: 'ai.checklist.suggest', scopes: ['own', 'team', 'portfolio'] },
    { permissionKey: 'bi.view', scopes: ['own', 'team', 'portfolio'] },
    { permissionKey: 'bi.snapshot.generate', scopes: ['own', 'team', 'portfolio'] },
    { permissionKey: 'timesheet.view', scopes: ['own', 'team', 'portfolio'] },
    { permissionKey: 'timesheet.entry.create', scopes: ['own', 'team', 'portfolio'] },
    { permissionKey: 'timesheet.entry.update', scopes: ['own', 'team', 'portfolio'] },
    { permissionKey: 'timesheet.entry.approve', scopes: ['own', 'team', 'portfolio'] },
    { permissionKey: 'timesheet.report.view', scopes: ['own', 'team', 'portfolio'] },
    { permissionKey: 'mobile.feed.view', scopes: ['own', 'team', 'portfolio'] },
  ],
  assistant: [
    { permissionKey: 'task.view', scopes: ['own', 'team'] },
    { permissionKey: 'task.create', scopes: ['own', 'team'] },
    { permissionKey: 'task.update', scopes: ['own', 'team'] },
    { permissionKey: 'task.followup.schedule', scopes: ['own', 'team'] },
    { permissionKey: 'attendance.view', scopes: ['own', 'team'] },
    { permissionKey: 'attendance.create', scopes: ['own', 'team'] },
    { permissionKey: 'attendance.updateSla', scopes: ['own', 'team'] },
    { permissionKey: 'attendance.convertToTask', scopes: ['own', 'team'] },
    { permissionKey: 'team.view', scopes: ['team'] },
    { permissionKey: 'portfolio.view', scopes: ['team'] },
    { permissionKey: 'productivity.view', scopes: ['own', 'team'] },
    { permissionKey: 'productivity.snapshot', scopes: ['own', 'team'] },
    { permissionKey: 'export.tasks', scopes: ['own', 'team'] },
    { permissionKey: 'export.attendances', scopes: ['own', 'team'] },
    { permissionKey: 'ai.view', scopes: ['own', 'team'] },
    { permissionKey: 'ai.summary.generate', scopes: ['own', 'team'] },
    { permissionKey: 'ai.checklist.suggest', scopes: ['own', 'team'] },
    { permissionKey: 'timesheet.view', scopes: ['own', 'team'] },
    { permissionKey: 'timesheet.entry.create', scopes: ['own', 'team'] },
    { permissionKey: 'timesheet.entry.update', scopes: ['own', 'team'] },
    { permissionKey: 'mobile.feed.view', scopes: ['own', 'team'] },
  ],
  company_finance: [
    { permissionKey: 'portfolio.view', scopes: ['global'] },
    { permissionKey: 'productivity.view', scopes: ['global'] },
    { permissionKey: 'productivity.snapshot', scopes: ['global'] },
    { permissionKey: 'productivity.export', scopes: ['global'] },
    { permissionKey: 'export.productivity', scopes: ['global'] },
    { permissionKey: 'bi.view', scopes: ['global'] },
    { permissionKey: 'bi.snapshot.generate', scopes: ['global'] },
    { permissionKey: 'bi.export.generate', scopes: ['global'] },
    { permissionKey: 'timesheet.view', scopes: ['global'] },
    { permissionKey: 'timesheet.report.view', scopes: ['global'] },
  ],
};

const platformRoleGrants: Record<PlatformRole, AuthzGrant[]> = {
  platform_admin: [{ permissionKey: 'portfolio.view', scopes: ['global'] }, { permissionKey: 'team.view', scopes: ['global'] }],
  platform_billing: [{ permissionKey: 'productivity.view', scopes: ['global'] }, { permissionKey: 'export.productivity', scopes: ['global'] }],
  platform_support: [{ permissionKey: 'attendance.view', scopes: ['global'] }, { permissionKey: 'task.view', scopes: ['global'] }],
};

export function listRoleGrants(role: AppRole, context: RoleContext): AuthzGrant[] {
  if (context === 'tenant') {
    return tenantRoleGrants[role as TenantRole] ?? [];
  }

  return platformRoleGrants[role as PlatformRole] ?? [];
}

